[build-system]
requires = ["setuptools", "setuptools-scm"]
requires-python = ">=3.10"
build-backend = "setuptools.build_meta"

[project]
name = "semantic_tagger"
version = "0.0.1"

dependencies = [
                "torch",
                "transformers",
                "accelerate",
                "bitsandbytes",
                "pandas",
                "trl",
                "datasets",
                "peft",
                "scipy",
                "scikit-learn",
               ]

[tool.setuptools.packages.find]
include = ["semtag"]
